### ISSUE TITLE
I did and I have the coph configuration problems when the command "make static" with ARM architecture. How his solution ?

### ISSUE THREAD

**Issue by SucianiUF** [russelldavies/coph#1]
![2](https://user-images.githubusercontent.com/31263720/29595355-1674dca0-87e1-11e7-8931-521a0481ca51.JPG)

**Comment by russelldavies** [comment]
It looks like you're running the command `make static` directly and you're using glibc. As it says in the README, you'll need musl installed or use the Docker build script by running `./build.sh`

**Comment by SucianiUF** [comment]
I've been doing install musl and Docker but nonetheless could not. is
there another
solution?

**Comment by russelldavies** [comment]
Okay, I can replicate this problem. The problem is the build script clones
the latest version of the CUPS repo. Either edit the script so that it's
cloning to a period in the past when this wasn't happening (January 2017
maybe). Or use one of the prebuild binaries, check the releases section.

**Comment by SucianiUF** [comment]
is there any configuration to declare CUPS_DNSSD_DESTS before?

**Comment by SucianiUF** [comment]
where do I get the latest version of CUP of repo?

**Comment by russelldavies** [comment]
I'm not sure about CUPS_DNSSD_DESTS, it's the first time I've seen it
undeclared as an error. I got CUPS to compile fine on an Ubuntu Docker
container so I think it's something to do with missing some DNS library in
Alpine Linux.

I would clone from https://github.com/apple/cups.git and checkout an older
version until it works.

**Comment by SucianiUF** [comment]
I use ARM, whether its configuration is the same?

**Comment by russelldavies** [comment]
Sorry, I'm not sure about this and don't have time to spend on it right now. If you don't need CUPS, have a look at [posh](http://github.com/russelldavies/posh) which should be easy enough to build.
